// Code generated by protoc-gen-dts. DO NOT EDIT.
// source: depscloud/api/v1beta/core.proto

export interface ProviderURL {
  provider: string;
  host: string;
  path: string;
  reference: string;
}

export interface Source {
  kind: string;
  url: string;
  labels: Source_LabelsEntry;
}

export type Source_LabelsEntry = { [key: string]: string }

export interface Module {
  language: string;
  name: string;
  labels: Module_LabelsEntry;
}

export type Module_LabelsEntry = { [key: string]: string }

export interface SourceModule {
  version: string;
  system: string;
  labels: SourceModule_LabelsEntry;
}

export type SourceModule_LabelsEntry = { [key: string]: string }

export interface ModuleDependency {
  ref: string;
  versionConstraint: string;
  scopes: Array<string>;
  labels: ModuleDependency_LabelsEntry;
}

export type ModuleDependency_LabelsEntry = { [key: string]: string }

