// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: depscloud/api/v1beta/core.proto

package v1beta

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProviderURL is a specifically formatted URI to create standard a standard
// representation for a source. The following shows example ProviderURL:
//  # General Format
//  - {provider}://{host}{path}#{reference}
//  # VCS Integrations
//  - github:///depscloud/tracker#main
//  - github://github.deps.cloud/oss/tracker#main
//  - gitlab:///depscloud/terraform#main
//  - gitlab://gitlab.deps.cloud/infra/terraform#main
//  - bitbucket:///depscloud/test#main
//  # Artifactory Integrations
//  - jfrog://jfrog.deps.cloud/oss/tracker#0.2.19
//  - nexus3://nexus3.deps.cloud/oss/tracker#0.2.19
type ProviderURL struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Reference            string   `protobuf:"bytes,4,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderURL) Reset()         { *m = ProviderURL{} }
func (m *ProviderURL) String() string { return proto.CompactTextString(m) }
func (*ProviderURL) ProtoMessage()    {}
func (*ProviderURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d5c495575bab3a, []int{0}
}
func (m *ProviderURL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderURL.Unmarshal(m, b)
}
func (m *ProviderURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderURL.Marshal(b, m, deterministic)
}
func (m *ProviderURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderURL.Merge(m, src)
}
func (m *ProviderURL) XXX_Size() int {
	return xxx_messageInfo_ProviderURL.Size(m)
}
func (m *ProviderURL) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderURL.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderURL proto.InternalMessageInfo

func (m *ProviderURL) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *ProviderURL) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ProviderURL) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ProviderURL) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// A source in depscloud represents an origin for information. This includes,
// but is not limited to, repositories and artifactories.
type Source struct {
	// The kind of source, typically repository or artifactory. This was kept
	// separate from the URL as systems like GitHub and GitLab offer some
	// artifact support.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// A string formatted ProviderURL
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Labels contain additional metadata about the entity
	Labels               map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d5c495575bab3a, []int{1}
}
func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Source) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Source) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// A module in depscloud is a generic representation of an application or library.
type Module struct {
	// The language associated with the module.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// The name of the application or library.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Labels contain additional metadata about the entity
	Labels               map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d5c495575bab3a, []int{2}
}
func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Module) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Module) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// SourceModule describes the relationship between a project and a module.
type SourceModule struct {
	// The language associated with the target module.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// The system used to manage dependencies for the target module.
	System string `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	// The version of the target module.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Labels contain additional metadata about the association
	Labels               map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SourceModule) Reset()         { *m = SourceModule{} }
func (m *SourceModule) String() string { return proto.CompactTextString(m) }
func (*SourceModule) ProtoMessage()    {}
func (*SourceModule) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d5c495575bab3a, []int{3}
}
func (m *SourceModule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceModule.Unmarshal(m, b)
}
func (m *SourceModule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceModule.Marshal(b, m, deterministic)
}
func (m *SourceModule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceModule.Merge(m, src)
}
func (m *SourceModule) XXX_Size() int {
	return xxx_messageInfo_SourceModule.Size(m)
}
func (m *SourceModule) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceModule.DiscardUnknown(m)
}

var xxx_messageInfo_SourceModule proto.InternalMessageInfo

func (m *SourceModule) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SourceModule) GetSystem() string {
	if m != nil {
		return m.System
	}
	return ""
}

func (m *SourceModule) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SourceModule) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// ModuleDependency describes the relationship between two modules. Because
// of this circular relationship, traditional database modeling is difficult.
type ModuleDependency struct {
	// The version associated with the module.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The version constraint defined by the project.
	VersionConstraint string `protobuf:"bytes,2,opt,name=version_constraint,json=versionConstraint,proto3" json:"version_constraint,omitempty"`
	// The scopes at which the requested module is needed.
	Scopes []string `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Labels contain additional metadata about the entity
	Labels               map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModuleDependency) Reset()         { *m = ModuleDependency{} }
func (m *ModuleDependency) String() string { return proto.CompactTextString(m) }
func (*ModuleDependency) ProtoMessage()    {}
func (*ModuleDependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d5c495575bab3a, []int{4}
}
func (m *ModuleDependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleDependency.Unmarshal(m, b)
}
func (m *ModuleDependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleDependency.Marshal(b, m, deterministic)
}
func (m *ModuleDependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleDependency.Merge(m, src)
}
func (m *ModuleDependency) XXX_Size() int {
	return xxx_messageInfo_ModuleDependency.Size(m)
}
func (m *ModuleDependency) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleDependency.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleDependency proto.InternalMessageInfo

func (m *ModuleDependency) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ModuleDependency) GetVersionConstraint() string {
	if m != nil {
		return m.VersionConstraint
	}
	return ""
}

func (m *ModuleDependency) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *ModuleDependency) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*ProviderURL)(nil), "depscloud.api.v1beta.ProviderURL")
	proto.RegisterType((*Source)(nil), "depscloud.api.v1beta.Source")
	proto.RegisterMapType((map[string]string)(nil), "depscloud.api.v1beta.Source.LabelsEntry")
	proto.RegisterType((*Module)(nil), "depscloud.api.v1beta.Module")
	proto.RegisterMapType((map[string]string)(nil), "depscloud.api.v1beta.Module.LabelsEntry")
	proto.RegisterType((*SourceModule)(nil), "depscloud.api.v1beta.SourceModule")
	proto.RegisterMapType((map[string]string)(nil), "depscloud.api.v1beta.SourceModule.LabelsEntry")
	proto.RegisterType((*ModuleDependency)(nil), "depscloud.api.v1beta.ModuleDependency")
	proto.RegisterMapType((map[string]string)(nil), "depscloud.api.v1beta.ModuleDependency.LabelsEntry")
}

func init() { proto.RegisterFile("depscloud/api/v1beta/core.proto", fileDescriptor_34d5c495575bab3a) }

var fileDescriptor_34d5c495575bab3a = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x95, 0x37, 0xbb, 0x81, 0x9d, 0x72, 0x58, 0xac, 0x15, 0x8a, 0x56, 0x48, 0x5b, 0x7a, 0xea,
	0x05, 0x47, 0x2c, 0x17, 0xe0, 0x84, 0xf8, 0x3a, 0xa0, 0x45, 0x42, 0x45, 0x5c, 0xb8, 0x20, 0xc7,
	0x19, 0xda, 0x68, 0x53, 0xdb, 0xb2, 0x9d, 0x48, 0xf9, 0x4d, 0x9c, 0xf9, 0x3d, 0xfc, 0x0f, 0x4e,
	0xc8, 0x8e, 0xd3, 0x96, 0xaa, 0xaa, 0x7a, 0x28, 0xb7, 0xf7, 0xc6, 0xf3, 0xf1, 0xde, 0x4c, 0x02,
	0xd7, 0x25, 0x6a, 0x2b, 0x6a, 0xd5, 0x94, 0x39, 0xd7, 0x55, 0xde, 0x3e, 0x2b, 0xd0, 0xf1, 0x5c,
	0x28, 0x83, 0x4c, 0x1b, 0xe5, 0x14, 0xbd, 0x5c, 0x25, 0x30, 0xae, 0x2b, 0xd6, 0x27, 0x4c, 0x14,
	0x8c, 0x3e, 0x1b, 0xd5, 0x56, 0x25, 0x9a, 0xaf, 0xb3, 0x5b, 0x7a, 0x05, 0xf7, 0x75, 0xa4, 0x19,
	0x19, 0x93, 0xe9, 0xf9, 0x6c, 0xc5, 0x29, 0x85, 0xd3, 0x85, 0xb2, 0x2e, 0x3b, 0x09, 0xf1, 0x80,
	0x7d, 0x4c, 0x73, 0xb7, 0xc8, 0x92, 0x3e, 0xe6, 0x31, 0x7d, 0x0c, 0xe7, 0x06, 0x7f, 0xa0, 0x41,
	0x29, 0x30, 0x3b, 0x0d, 0x0f, 0xeb, 0xc0, 0xe4, 0x27, 0x81, 0xf4, 0x8b, 0x6a, 0x8c, 0x40, 0x5f,
	0x7c, 0x57, 0xc9, 0x32, 0x0e, 0x0a, 0x98, 0x5e, 0x40, 0xd2, 0x98, 0x3a, 0xce, 0xf0, 0x90, 0xbe,
	0x86, 0xb4, 0xe6, 0x05, 0xd6, 0x36, 0x3b, 0x1b, 0x27, 0xd3, 0xd1, 0xcd, 0x94, 0xed, 0x32, 0xc2,
	0xfa, 0x9e, 0xec, 0x36, 0xa4, 0xbe, 0x97, 0xce, 0x74, 0xb3, 0x58, 0x77, 0xf5, 0x12, 0x46, 0x1b,
	0x61, 0x3f, 0xe2, 0x0e, 0xbb, 0x38, 0xd5, 0x43, 0x7a, 0x09, 0x67, 0x2d, 0xaf, 0x1b, 0x8c, 0x63,
	0x7b, 0xf2, 0xea, 0xe4, 0x05, 0x99, 0xfc, 0x22, 0x90, 0x7e, 0x52, 0x65, 0x53, 0xa3, 0x5f, 0x4d,
	0xcd, 0xe5, 0xbc, 0xe1, 0x73, 0x1c, 0x56, 0x33, 0x70, 0xef, 0x44, 0xf2, 0xe5, 0x50, 0x1f, 0xf0,
	0xa1, 0xba, 0xfb, 0xee, 0xc7, 0xd6, 0xfd, 0x9b, 0xc0, 0x83, 0x7e, 0x23, 0x07, 0xa8, 0x7f, 0x04,
	0xa9, 0xed, 0xac, 0xc3, 0x65, 0xec, 0x13, 0x19, 0xcd, 0xe0, 0x5e, 0x8b, 0xc6, 0x56, 0x4a, 0xc6,
	0xfb, 0x0e, 0x94, 0x7e, 0xd8, 0xf2, 0xc6, 0xf6, 0xdd, 0xe4, 0xff, 0x38, 0xfc, 0x43, 0xe0, 0xa2,
	0xef, 0xfc, 0x0e, 0x35, 0xca, 0x12, 0xa5, 0xe8, 0x36, 0x15, 0x93, 0x7f, 0x15, 0x3f, 0x05, 0x1a,
	0xe1, 0x77, 0xa1, 0xa4, 0x75, 0x86, 0x57, 0x72, 0xf8, 0x94, 0x1f, 0xc6, 0x97, 0xb7, 0xab, 0x87,
	0xb0, 0x12, 0xa1, 0x34, 0xda, 0x2c, 0x19, 0x27, 0x61, 0x25, 0x81, 0xd1, 0x8f, 0x5b, 0xc6, 0x6f,
	0xf6, 0x1d, 0x75, 0x2d, 0xec, 0xc8, 0xe6, 0xdf, 0x3c, 0xf9, 0x76, 0x3d, 0xaf, 0xdc, 0xa2, 0x29,
	0x98, 0x50, 0xcb, 0x7c, 0xd7, 0x9f, 0x5f, 0xa4, 0xe1, 0xaf, 0x7f, 0xfe, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x66, 0x33, 0x6c, 0x3d, 0x18, 0x04, 0x00, 0x00,
}
