// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: depscloud/api/v1beta/rpc.proto

package v1beta

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{0}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListSourcesResponse struct {
	NextPageToken        string    `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Sources              []*Source `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListSourcesResponse) Reset()         { *m = ListSourcesResponse{} }
func (m *ListSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ListSourcesResponse) ProtoMessage()    {}
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{1}
}
func (m *ListSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSourcesResponse.Unmarshal(m, b)
}
func (m *ListSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSourcesResponse.Marshal(b, m, deterministic)
}
func (m *ListSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSourcesResponse.Merge(m, src)
}
func (m *ListSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ListSourcesResponse.Size(m)
}
func (m *ListSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSourcesResponse proto.InternalMessageInfo

func (m *ListSourcesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListSourcesResponse) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ListModulesResponse struct {
	NextPageToken        string    `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Modules              []*Module `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListModulesResponse) Reset()         { *m = ListModulesResponse{} }
func (m *ListModulesResponse) String() string { return proto.CompactTextString(m) }
func (*ListModulesResponse) ProtoMessage()    {}
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{2}
}
func (m *ListModulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModulesResponse.Unmarshal(m, b)
}
func (m *ListModulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModulesResponse.Marshal(b, m, deterministic)
}
func (m *ListModulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModulesResponse.Merge(m, src)
}
func (m *ListModulesResponse) XXX_Size() int {
	return xxx_messageInfo_ListModulesResponse.Size(m)
}
func (m *ListModulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListModulesResponse proto.InternalMessageInfo

func (m *ListModulesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListModulesResponse) GetModules() []*Module {
	if m != nil {
		return m.Modules
	}
	return nil
}

type ManagedModule struct {
	Module               *Module         `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	EdgeData             []*SourceModule `protobuf:"bytes,2,rep,name=edge_data,json=edgeData,proto3" json:"edge_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ManagedModule) Reset()         { *m = ManagedModule{} }
func (m *ManagedModule) String() string { return proto.CompactTextString(m) }
func (*ManagedModule) ProtoMessage()    {}
func (*ManagedModule) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{3}
}
func (m *ManagedModule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedModule.Unmarshal(m, b)
}
func (m *ManagedModule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedModule.Marshal(b, m, deterministic)
}
func (m *ManagedModule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedModule.Merge(m, src)
}
func (m *ManagedModule) XXX_Size() int {
	return xxx_messageInfo_ManagedModule.Size(m)
}
func (m *ManagedModule) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedModule.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedModule proto.InternalMessageInfo

func (m *ManagedModule) GetModule() *Module {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *ManagedModule) GetEdgeData() []*SourceModule {
	if m != nil {
		return m.EdgeData
	}
	return nil
}

type ManagedSource struct {
	Source               *Source         `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	EdgeData             []*SourceModule `protobuf:"bytes,2,rep,name=edge_data,json=edgeData,proto3" json:"edge_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ManagedSource) Reset()         { *m = ManagedSource{} }
func (m *ManagedSource) String() string { return proto.CompactTextString(m) }
func (*ManagedSource) ProtoMessage()    {}
func (*ManagedSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{4}
}
func (m *ManagedSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedSource.Unmarshal(m, b)
}
func (m *ManagedSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedSource.Marshal(b, m, deterministic)
}
func (m *ManagedSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedSource.Merge(m, src)
}
func (m *ManagedSource) XXX_Size() int {
	return xxx_messageInfo_ManagedSource.Size(m)
}
func (m *ManagedSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedSource.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedSource proto.InternalMessageInfo

func (m *ManagedSource) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *ManagedSource) GetEdgeData() []*SourceModule {
	if m != nil {
		return m.EdgeData
	}
	return nil
}

type ListManagedSourcesResponse struct {
	Sources              []*ManagedSource `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListManagedSourcesResponse) Reset()         { *m = ListManagedSourcesResponse{} }
func (m *ListManagedSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ListManagedSourcesResponse) ProtoMessage()    {}
func (*ListManagedSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{5}
}
func (m *ListManagedSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManagedSourcesResponse.Unmarshal(m, b)
}
func (m *ListManagedSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManagedSourcesResponse.Marshal(b, m, deterministic)
}
func (m *ListManagedSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManagedSourcesResponse.Merge(m, src)
}
func (m *ListManagedSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ListManagedSourcesResponse.Size(m)
}
func (m *ListManagedSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManagedSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListManagedSourcesResponse proto.InternalMessageInfo

func (m *ListManagedSourcesResponse) GetSources() []*ManagedSource {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ListManagedModulesResponse struct {
	Modules              []*ManagedModule `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListManagedModulesResponse) Reset()         { *m = ListManagedModulesResponse{} }
func (m *ListManagedModulesResponse) String() string { return proto.CompactTextString(m) }
func (*ListManagedModulesResponse) ProtoMessage()    {}
func (*ListManagedModulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{6}
}
func (m *ListManagedModulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManagedModulesResponse.Unmarshal(m, b)
}
func (m *ListManagedModulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManagedModulesResponse.Marshal(b, m, deterministic)
}
func (m *ListManagedModulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManagedModulesResponse.Merge(m, src)
}
func (m *ListManagedModulesResponse) XXX_Size() int {
	return xxx_messageInfo_ListManagedModulesResponse.Size(m)
}
func (m *ListManagedModulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManagedModulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListManagedModulesResponse proto.InternalMessageInfo

func (m *ListManagedModulesResponse) GetModules() []*ManagedModule {
	if m != nil {
		return m.Modules
	}
	return nil
}

type Dependency struct {
	Module               *Module             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	EdgeData             []*ModuleDependency `protobuf:"bytes,2,rep,name=edge_data,json=edgeData,proto3" json:"edge_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{7}
}
func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetModule() *Module {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *Dependency) GetEdgeData() []*ModuleDependency {
	if m != nil {
		return m.EdgeData
	}
	return nil
}

type DependentsResponse struct {
	Dependents           []*Dependency `protobuf:"bytes,1,rep,name=dependents,proto3" json:"dependents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DependentsResponse) Reset()         { *m = DependentsResponse{} }
func (m *DependentsResponse) String() string { return proto.CompactTextString(m) }
func (*DependentsResponse) ProtoMessage()    {}
func (*DependentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{8}
}
func (m *DependentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependentsResponse.Unmarshal(m, b)
}
func (m *DependentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependentsResponse.Marshal(b, m, deterministic)
}
func (m *DependentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependentsResponse.Merge(m, src)
}
func (m *DependentsResponse) XXX_Size() int {
	return xxx_messageInfo_DependentsResponse.Size(m)
}
func (m *DependentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DependentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DependentsResponse proto.InternalMessageInfo

func (m *DependentsResponse) GetDependents() []*Dependency {
	if m != nil {
		return m.Dependents
	}
	return nil
}

type DependenciesResponse struct {
	Dependencies         []*Dependency `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DependenciesResponse) Reset()         { *m = DependenciesResponse{} }
func (m *DependenciesResponse) String() string { return proto.CompactTextString(m) }
func (*DependenciesResponse) ProtoMessage()    {}
func (*DependenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{9}
}
func (m *DependenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependenciesResponse.Unmarshal(m, b)
}
func (m *DependenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependenciesResponse.Marshal(b, m, deterministic)
}
func (m *DependenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependenciesResponse.Merge(m, src)
}
func (m *DependenciesResponse) XXX_Size() int {
	return xxx_messageInfo_DependenciesResponse.Size(m)
}
func (m *DependenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DependenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DependenciesResponse proto.InternalMessageInfo

func (m *DependenciesResponse) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type SearchRequest struct {
	Cancel               bool           `protobuf:"varint,1,opt,name=cancel,proto3" json:"cancel,omitempty"`
	ModulesFor           *ManagedSource `protobuf:"bytes,5,opt,name=modules_for,json=modulesFor,proto3" json:"modules_for,omitempty"`
	DependenciesFor      *Dependency    `protobuf:"bytes,6,opt,name=dependencies_for,json=dependenciesFor,proto3" json:"dependencies_for,omitempty"`
	DependentsOf         *Dependency    `protobuf:"bytes,7,opt,name=dependents_of,json=dependentsOf,proto3" json:"dependents_of,omitempty"`
	SourcesOf            *ManagedModule `protobuf:"bytes,8,opt,name=sources_of,json=sourcesOf,proto3" json:"sources_of,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{10}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetCancel() bool {
	if m != nil {
		return m.Cancel
	}
	return false
}

func (m *SearchRequest) GetModulesFor() *ManagedSource {
	if m != nil {
		return m.ModulesFor
	}
	return nil
}

func (m *SearchRequest) GetDependenciesFor() *Dependency {
	if m != nil {
		return m.DependenciesFor
	}
	return nil
}

func (m *SearchRequest) GetDependentsOf() *Dependency {
	if m != nil {
		return m.DependentsOf
	}
	return nil
}

func (m *SearchRequest) GetSourcesOf() *ManagedModule {
	if m != nil {
		return m.SourcesOf
	}
	return nil
}

type SearchResponse struct {
	Request              *SearchRequest   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Modules              []*ManagedModule `protobuf:"bytes,5,rep,name=modules,proto3" json:"modules,omitempty"`
	Dependencies         []*Dependency    `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Dependents           []*Dependency    `protobuf:"bytes,7,rep,name=dependents,proto3" json:"dependents,omitempty"`
	Sources              []*ManagedSource `protobuf:"bytes,8,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa407514c2c45ed4, []int{11}
}
func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetRequest() *SearchRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SearchResponse) GetModules() []*ManagedModule {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *SearchResponse) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *SearchResponse) GetDependents() []*Dependency {
	if m != nil {
		return m.Dependents
	}
	return nil
}

func (m *SearchResponse) GetSources() []*ManagedSource {
	if m != nil {
		return m.Sources
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "depscloud.api.v1beta.ListRequest")
	proto.RegisterType((*ListSourcesResponse)(nil), "depscloud.api.v1beta.ListSourcesResponse")
	proto.RegisterType((*ListModulesResponse)(nil), "depscloud.api.v1beta.ListModulesResponse")
	proto.RegisterType((*ManagedModule)(nil), "depscloud.api.v1beta.ManagedModule")
	proto.RegisterType((*ManagedSource)(nil), "depscloud.api.v1beta.ManagedSource")
	proto.RegisterType((*ListManagedSourcesResponse)(nil), "depscloud.api.v1beta.ListManagedSourcesResponse")
	proto.RegisterType((*ListManagedModulesResponse)(nil), "depscloud.api.v1beta.ListManagedModulesResponse")
	proto.RegisterType((*Dependency)(nil), "depscloud.api.v1beta.Dependency")
	proto.RegisterType((*DependentsResponse)(nil), "depscloud.api.v1beta.DependentsResponse")
	proto.RegisterType((*DependenciesResponse)(nil), "depscloud.api.v1beta.DependenciesResponse")
	proto.RegisterType((*SearchRequest)(nil), "depscloud.api.v1beta.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "depscloud.api.v1beta.SearchResponse")
}

func init() { proto.RegisterFile("depscloud/api/v1beta/rpc.proto", fileDescriptor_aa407514c2c45ed4) }

var fileDescriptor_aa407514c2c45ed4 = []byte{
	// 726 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0xd3, 0x5f, 0xd3, 0x64, 0xda, 0xfc, 0x5a, 0x2d, 0x15, 0x8a, 0xc2, 0x9f, 0xa6, 0x06,
	0x55, 0x81, 0x43, 0x52, 0x0a, 0xe2, 0x56, 0x81, 0x4a, 0x28, 0x07, 0xa8, 0x8a, 0x9c, 0x0a, 0x24,
	0x8a, 0x14, 0x6d, 0xed, 0x49, 0x6a, 0x91, 0x7a, 0xcd, 0x7a, 0x53, 0x41, 0x1f, 0x00, 0x9e, 0x8c,
	0x13, 0x67, 0x1e, 0x84, 0x37, 0x40, 0xde, 0x5d, 0xd7, 0xdb, 0x34, 0x71, 0xdc, 0x40, 0x8f, 0x99,
	0x99, 0xef, 0x9b, 0x99, 0x6f, 0x66, 0x27, 0x86, 0xbb, 0x1e, 0x86, 0x91, 0x3b, 0x60, 0x43, 0xaf,
	0x45, 0x43, 0xbf, 0x75, 0xfa, 0xe8, 0x08, 0x05, 0x6d, 0xf1, 0xd0, 0x6d, 0x86, 0x9c, 0x09, 0x46,
	0x56, 0xcf, 0xfd, 0x4d, 0x1a, 0xfa, 0x4d, 0xe5, 0xaf, 0xad, 0x8d, 0x45, 0xb9, 0x8c, 0xa3, 0x82,
	0xd9, 0x14, 0x16, 0xdf, 0xf8, 0x91, 0x70, 0xf0, 0xf3, 0x10, 0x23, 0x41, 0x6e, 0x42, 0x31, 0xa4,
	0x1c, 0x03, 0x51, 0xb5, 0xea, 0x56, 0xa3, 0xec, 0xe8, 0x5f, 0xe4, 0x16, 0x94, 0x43, 0xda, 0xc7,
	0x6e, 0xe4, 0x9f, 0x61, 0xb5, 0x50, 0xb7, 0x1a, 0xf3, 0x4e, 0x29, 0x36, 0x74, 0xfc, 0x33, 0x24,
	0x77, 0x00, 0xa4, 0x53, 0xb0, 0x4f, 0x18, 0x54, 0xe7, 0x24, 0x50, 0x86, 0x1f, 0xc4, 0x06, 0x7b,
	0x08, 0x37, 0xe2, 0x14, 0x1d, 0x36, 0xe4, 0x2e, 0x46, 0x0e, 0x46, 0x21, 0x0b, 0x22, 0x24, 0x1b,
	0xb0, 0x1c, 0xe0, 0x17, 0xd1, 0x35, 0xa0, 0x2a, 0x67, 0x25, 0x36, 0xbf, 0x4d, 0xe0, 0xe4, 0x29,
	0x2c, 0x44, 0x0a, 0x5a, 0x2d, 0xd4, 0xe7, 0x1a, 0x8b, 0x5b, 0xb7, 0x9b, 0xe3, 0x5a, 0x6d, 0x2a,
	0x7e, 0x27, 0x09, 0x4e, 0xd2, 0xee, 0x31, 0x6f, 0x38, 0x98, 0x2d, 0xed, 0x89, 0x82, 0x66, 0xa7,
	0x55, 0xfc, 0x4e, 0x12, 0x6c, 0x7f, 0xb3, 0xa0, 0xb2, 0x47, 0x03, 0xda, 0x47, 0x4f, 0xb9, 0xc8,
	0x13, 0x28, 0x2a, 0xa7, 0x4c, 0x34, 0x8d, 0x48, 0xc7, 0x92, 0x67, 0x50, 0x46, 0xaf, 0x8f, 0x5d,
	0x8f, 0x0a, 0xaa, 0x2b, 0xb0, 0xb3, 0x1a, 0xd7, 0xf0, 0x52, 0x0c, 0x6a, 0x53, 0x41, 0xcd, 0x42,
	0x54, 0x44, 0x5c, 0x88, 0x12, 0x27, 0xbb, 0x10, 0x2d, 0xa4, 0x8e, 0xfd, 0xfb, 0x42, 0x0e, 0xa1,
	0x26, 0x07, 0x61, 0xd6, 0x92, 0xce, 0x63, 0x3b, 0x1d, 0xaf, 0x25, 0xc9, 0xef, 0x4d, 0x90, 0xc7,
	0x84, 0xa7, 0x53, 0xbe, 0x48, 0x3e, 0x3a, 0xec, 0xed, 0x74, 0x88, 0x79, 0xc8, 0x47, 0x67, 0xf9,
	0xdd, 0x02, 0x68, 0x63, 0x88, 0x81, 0x87, 0x81, 0xfb, 0x75, 0xc6, 0x41, 0xbe, 0xb8, 0xac, 0xdf,
	0x46, 0x16, 0x30, 0x4d, 0x68, 0x68, 0xf8, 0x0e, 0x48, 0x62, 0x17, 0x69, 0x7b, 0xcf, 0x01, 0xbc,
	0x73, 0xab, 0xee, 0xb0, 0x3e, 0x9e, 0xdb, 0x60, 0x35, 0x30, 0xf6, 0x47, 0x58, 0x3d, 0xf7, 0xf8,
	0x86, 0x70, 0x6d, 0x58, 0xf2, 0x0c, 0x7b, 0x6e, 0xee, 0x0b, 0x28, 0xfb, 0x47, 0x01, 0x2a, 0x1d,
	0xa4, 0xdc, 0x3d, 0x36, 0xee, 0x8b, 0x4b, 0x03, 0x17, 0x07, 0x52, 0xc2, 0x92, 0xa3, 0x7f, 0x91,
	0x36, 0x2c, 0x6a, 0xd1, 0xbb, 0x3d, 0xc6, 0xab, 0xf3, 0x52, 0xdf, 0x5c, 0x9b, 0x00, 0x1a, 0xb7,
	0xcb, 0x38, 0x79, 0x0d, 0x2b, 0x66, 0x7e, 0x49, 0x55, 0x94, 0x54, 0xd3, 0x2b, 0x5f, 0x36, 0x91,
	0x31, 0xd9, 0x4b, 0xa8, 0xa4, 0x42, 0x75, 0x59, 0xaf, 0xba, 0x90, 0x93, 0x69, 0x29, 0x85, 0xed,
	0xf7, 0xc8, 0x0e, 0x80, 0xde, 0xd5, 0x98, 0xa3, 0x94, 0xa3, 0x31, 0xbd, 0x3f, 0x65, 0x0d, 0xdb,
	0xef, 0xd9, 0xbf, 0x0a, 0xf0, 0x7f, 0xa2, 0x63, 0xba, 0xd9, 0x5c, 0x69, 0xaa, 0x97, 0x71, 0x02,
	0xe7, 0x05, 0xf9, 0x9d, 0x04, 0x63, 0x3e, 0x8c, 0xf9, 0xab, 0x3f, 0x8c, 0x4b, 0xeb, 0x51, 0x9c,
	0x65, 0x3d, 0x46, 0xd6, 0x77, 0xe1, 0xea, 0xeb, 0x6b, 0x1e, 0x8f, 0xd2, 0xd5, 0x8f, 0xc7, 0xd6,
	0x4f, 0x0b, 0x2a, 0xca, 0xd6, 0x41, 0x7e, 0xea, 0xbb, 0x48, 0x0e, 0xe0, 0xbf, 0xf8, 0x9c, 0x90,
	0xf5, 0xf1, 0x3c, 0xc6, 0x5f, 0x65, 0xed, 0xc1, 0xe4, 0x90, 0xd1, 0x1b, 0xe7, 0xa9, 0x3f, 0x59,
	0x7d, 0x9d, 0x48, 0x9e, 0x22, 0x6b, 0x9b, 0x93, 0xe9, 0xc7, 0x1f, 0x3b, 0xd9, 0x8d, 0xb2, 0xfd,
	0xdb, 0x6e, 0x46, 0x8f, 0xaa, 0xee, 0x46, 0x37, 0x49, 0xf2, 0x6c, 0x4e, 0x8e, 0x6e, 0x46, 0x34,
	0xdb, 0xfa, 0x3d, 0x07, 0x2b, 0x07, 0x9c, 0x9e, 0x22, 0x8f, 0xe8, 0x20, 0x69, 0xe8, 0x10, 0x2a,
	0xaf, 0x50, 0xa4, 0x97, 0x90, 0x4c, 0x5d, 0x97, 0x5a, 0x23, 0x3b, 0xc2, 0xb8, 0xa6, 0x5d, 0x58,
	0x36, 0xc8, 0xe5, 0x86, 0x4e, 0xa7, 0x7f, 0x38, 0x25, 0xc2, 0x3c, 0xaa, 0xef, 0xa1, 0xa8, 0x9e,
	0x23, 0xc9, 0xf3, 0x58, 0x6b, 0xf7, 0xb3, 0x83, 0x14, 0x69, 0xc3, 0xda, 0xb4, 0x88, 0x0b, 0x64,
	0x87, 0x23, 0xf5, 0xc4, 0xf1, 0xae, 0xcf, 0x23, 0x71, 0x3d, 0x49, 0x28, 0xac, 0xb4, 0x31, 0xbc,
	0xce, 0x14, 0x3b, 0xeb, 0x1f, 0xd6, 0xfa, 0xbe, 0x38, 0x1e, 0x1e, 0x35, 0x5d, 0x76, 0xd2, 0x1a,
	0xf7, 0xe9, 0x7a, 0x54, 0x94, 0x9f, 0xad, 0x8f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x82, 0x08,
	0xfb, 0xc2, 0x0f, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SourceServiceClient is the client API for SourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SourceServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	ListModules(ctx context.Context, in *ManagedSource, opts ...grpc.CallOption) (*ListManagedModulesResponse, error)
}

type sourceServiceClient struct {
	cc *grpc.ClientConn
}

func NewSourceServiceClient(cc *grpc.ClientConn) SourceServiceClient {
	return &sourceServiceClient{cc}
}

func (c *sourceServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, "/depscloud.api.v1beta.SourceService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) ListModules(ctx context.Context, in *ManagedSource, opts ...grpc.CallOption) (*ListManagedModulesResponse, error) {
	out := new(ListManagedModulesResponse)
	err := c.cc.Invoke(ctx, "/depscloud.api.v1beta.SourceService/ListModules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServiceServer is the server API for SourceService service.
type SourceServiceServer interface {
	List(context.Context, *ListRequest) (*ListSourcesResponse, error)
	ListModules(context.Context, *ManagedSource) (*ListManagedModulesResponse, error)
}

// UnimplementedSourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSourceServiceServer struct {
}

func (*UnimplementedSourceServiceServer) List(ctx context.Context, req *ListRequest) (*ListSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedSourceServiceServer) ListModules(ctx context.Context, req *ManagedSource) (*ListManagedModulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModules not implemented")
}

func RegisterSourceServiceServer(s *grpc.Server, srv SourceServiceServer) {
	s.RegisterService(&_SourceService_serviceDesc, srv)
}

func _SourceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depscloud.api.v1beta.SourceService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagedSource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depscloud.api.v1beta.SourceService/ListModules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).ListModules(ctx, req.(*ManagedSource))
	}
	return interceptor(ctx, in, info, handler)
}

var _SourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "depscloud.api.v1beta.SourceService",
	HandlerType: (*SourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SourceService_List_Handler,
		},
		{
			MethodName: "ListModules",
			Handler:    _SourceService_ListModules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "depscloud/api/v1beta/rpc.proto",
}

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListModulesResponse, error)
	ListSources(ctx context.Context, in *ManagedModule, opts ...grpc.CallOption) (*ListManagedSourcesResponse, error)
}

type moduleServiceClient struct {
	cc *grpc.ClientConn
}

func NewModuleServiceClient(cc *grpc.ClientConn) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListModulesResponse, error) {
	out := new(ListModulesResponse)
	err := c.cc.Invoke(ctx, "/depscloud.api.v1beta.ModuleService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) ListSources(ctx context.Context, in *ManagedModule, opts ...grpc.CallOption) (*ListManagedSourcesResponse, error) {
	out := new(ListManagedSourcesResponse)
	err := c.cc.Invoke(ctx, "/depscloud.api.v1beta.ModuleService/ListSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServiceServer is the server API for ModuleService service.
type ModuleServiceServer interface {
	List(context.Context, *ListRequest) (*ListModulesResponse, error)
	ListSources(context.Context, *ManagedModule) (*ListManagedSourcesResponse, error)
}

// UnimplementedModuleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedModuleServiceServer struct {
}

func (*UnimplementedModuleServiceServer) List(ctx context.Context, req *ListRequest) (*ListModulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedModuleServiceServer) ListSources(ctx context.Context, req *ManagedModule) (*ListManagedSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}

func RegisterModuleServiceServer(s *grpc.Server, srv ModuleServiceServer) {
	s.RegisterService(&_ModuleService_serviceDesc, srv)
}

func _ModuleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depscloud.api.v1beta.ModuleService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagedModule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depscloud.api.v1beta.ModuleService/ListSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).ListSources(ctx, req.(*ManagedModule))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "depscloud.api.v1beta.ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ModuleService_List_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _ModuleService_ListSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "depscloud/api/v1beta/rpc.proto",
}

// TraversalServiceClient is the client API for TraversalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TraversalServiceClient interface {
	GetDependents(ctx context.Context, in *Dependency, opts ...grpc.CallOption) (*DependentsResponse, error)
	GetDependencies(ctx context.Context, in *Dependency, opts ...grpc.CallOption) (*DependenciesResponse, error)
	Search(ctx context.Context, opts ...grpc.CallOption) (TraversalService_SearchClient, error)
	BreadthFirstSearch(ctx context.Context, opts ...grpc.CallOption) (TraversalService_BreadthFirstSearchClient, error)
	DepthFirstSearch(ctx context.Context, opts ...grpc.CallOption) (TraversalService_DepthFirstSearchClient, error)
}

type traversalServiceClient struct {
	cc *grpc.ClientConn
}

func NewTraversalServiceClient(cc *grpc.ClientConn) TraversalServiceClient {
	return &traversalServiceClient{cc}
}

func (c *traversalServiceClient) GetDependents(ctx context.Context, in *Dependency, opts ...grpc.CallOption) (*DependentsResponse, error) {
	out := new(DependentsResponse)
	err := c.cc.Invoke(ctx, "/depscloud.api.v1beta.TraversalService/GetDependents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traversalServiceClient) GetDependencies(ctx context.Context, in *Dependency, opts ...grpc.CallOption) (*DependenciesResponse, error) {
	out := new(DependenciesResponse)
	err := c.cc.Invoke(ctx, "/depscloud.api.v1beta.TraversalService/GetDependencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traversalServiceClient) Search(ctx context.Context, opts ...grpc.CallOption) (TraversalService_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TraversalService_serviceDesc.Streams[0], "/depscloud.api.v1beta.TraversalService/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &traversalServiceSearchClient{stream}
	return x, nil
}

type TraversalService_SearchClient interface {
	Send(*SearchRequest) error
	Recv() (*SearchResponse, error)
	grpc.ClientStream
}

type traversalServiceSearchClient struct {
	grpc.ClientStream
}

func (x *traversalServiceSearchClient) Send(m *SearchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *traversalServiceSearchClient) Recv() (*SearchResponse, error) {
	m := new(SearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *traversalServiceClient) BreadthFirstSearch(ctx context.Context, opts ...grpc.CallOption) (TraversalService_BreadthFirstSearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TraversalService_serviceDesc.Streams[1], "/depscloud.api.v1beta.TraversalService/BreadthFirstSearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &traversalServiceBreadthFirstSearchClient{stream}
	return x, nil
}

type TraversalService_BreadthFirstSearchClient interface {
	Send(*SearchRequest) error
	Recv() (*SearchResponse, error)
	grpc.ClientStream
}

type traversalServiceBreadthFirstSearchClient struct {
	grpc.ClientStream
}

func (x *traversalServiceBreadthFirstSearchClient) Send(m *SearchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *traversalServiceBreadthFirstSearchClient) Recv() (*SearchResponse, error) {
	m := new(SearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *traversalServiceClient) DepthFirstSearch(ctx context.Context, opts ...grpc.CallOption) (TraversalService_DepthFirstSearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TraversalService_serviceDesc.Streams[2], "/depscloud.api.v1beta.TraversalService/DepthFirstSearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &traversalServiceDepthFirstSearchClient{stream}
	return x, nil
}

type TraversalService_DepthFirstSearchClient interface {
	Send(*SearchRequest) error
	Recv() (*SearchResponse, error)
	grpc.ClientStream
}

type traversalServiceDepthFirstSearchClient struct {
	grpc.ClientStream
}

func (x *traversalServiceDepthFirstSearchClient) Send(m *SearchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *traversalServiceDepthFirstSearchClient) Recv() (*SearchResponse, error) {
	m := new(SearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TraversalServiceServer is the server API for TraversalService service.
type TraversalServiceServer interface {
	GetDependents(context.Context, *Dependency) (*DependentsResponse, error)
	GetDependencies(context.Context, *Dependency) (*DependenciesResponse, error)
	Search(TraversalService_SearchServer) error
	BreadthFirstSearch(TraversalService_BreadthFirstSearchServer) error
	DepthFirstSearch(TraversalService_DepthFirstSearchServer) error
}

// UnimplementedTraversalServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTraversalServiceServer struct {
}

func (*UnimplementedTraversalServiceServer) GetDependents(ctx context.Context, req *Dependency) (*DependentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependents not implemented")
}
func (*UnimplementedTraversalServiceServer) GetDependencies(ctx context.Context, req *Dependency) (*DependenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependencies not implemented")
}
func (*UnimplementedTraversalServiceServer) Search(srv TraversalService_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedTraversalServiceServer) BreadthFirstSearch(srv TraversalService_BreadthFirstSearchServer) error {
	return status.Errorf(codes.Unimplemented, "method BreadthFirstSearch not implemented")
}
func (*UnimplementedTraversalServiceServer) DepthFirstSearch(srv TraversalService_DepthFirstSearchServer) error {
	return status.Errorf(codes.Unimplemented, "method DepthFirstSearch not implemented")
}

func RegisterTraversalServiceServer(s *grpc.Server, srv TraversalServiceServer) {
	s.RegisterService(&_TraversalService_serviceDesc, srv)
}

func _TraversalService_GetDependents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dependency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraversalServiceServer).GetDependents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depscloud.api.v1beta.TraversalService/GetDependents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraversalServiceServer).GetDependents(ctx, req.(*Dependency))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraversalService_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dependency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraversalServiceServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depscloud.api.v1beta.TraversalService/GetDependencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraversalServiceServer).GetDependencies(ctx, req.(*Dependency))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraversalService_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TraversalServiceServer).Search(&traversalServiceSearchServer{stream})
}

type TraversalService_SearchServer interface {
	Send(*SearchResponse) error
	Recv() (*SearchRequest, error)
	grpc.ServerStream
}

type traversalServiceSearchServer struct {
	grpc.ServerStream
}

func (x *traversalServiceSearchServer) Send(m *SearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *traversalServiceSearchServer) Recv() (*SearchRequest, error) {
	m := new(SearchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TraversalService_BreadthFirstSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TraversalServiceServer).BreadthFirstSearch(&traversalServiceBreadthFirstSearchServer{stream})
}

type TraversalService_BreadthFirstSearchServer interface {
	Send(*SearchResponse) error
	Recv() (*SearchRequest, error)
	grpc.ServerStream
}

type traversalServiceBreadthFirstSearchServer struct {
	grpc.ServerStream
}

func (x *traversalServiceBreadthFirstSearchServer) Send(m *SearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *traversalServiceBreadthFirstSearchServer) Recv() (*SearchRequest, error) {
	m := new(SearchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TraversalService_DepthFirstSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TraversalServiceServer).DepthFirstSearch(&traversalServiceDepthFirstSearchServer{stream})
}

type TraversalService_DepthFirstSearchServer interface {
	Send(*SearchResponse) error
	Recv() (*SearchRequest, error)
	grpc.ServerStream
}

type traversalServiceDepthFirstSearchServer struct {
	grpc.ServerStream
}

func (x *traversalServiceDepthFirstSearchServer) Send(m *SearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *traversalServiceDepthFirstSearchServer) Recv() (*SearchRequest, error) {
	m := new(SearchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TraversalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "depscloud.api.v1beta.TraversalService",
	HandlerType: (*TraversalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDependents",
			Handler:    _TraversalService_GetDependents_Handler,
		},
		{
			MethodName: "GetDependencies",
			Handler:    _TraversalService_GetDependencies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _TraversalService_Search_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "BreadthFirstSearch",
			Handler:       _TraversalService_BreadthFirstSearch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DepthFirstSearch",
			Handler:       _TraversalService_DepthFirstSearch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "depscloud/api/v1beta/rpc.proto",
}
