# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from examples.internal.proto.pathenum import path_enum_pb2 as examples_dot_internal_dot_proto_dot_pathenum_dot_path__enum__pb2
from examples.internal.proto.sub import message_pb2 as examples_dot_internal_dot_proto_dot_sub_dot_message__pb2
from examples.internal.proto.sub2 import message_pb2 as examples_dot_internal_dot_proto_dot_sub2_dot_message__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from grpc_gateway.examples.internal.proto.examplepb import a_bit_of_everything_pb2 as grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2


class ABitOfEverythingServiceStub(object):
    """ABitOfEverything service is used to validate that APIs with complicated
    proto messages and URL templates are still processed correctly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Create',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                )
        self.CreateBody = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CreateBody',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                )
        self.Lookup = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Lookup',
                request_serializer=examples_dot_internal_dot_proto_dot_sub2_dot_message__pb2.IdMessage.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                )
        self.Update = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Update',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateV2 = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/UpdateV2',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.UpdateV2Request.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Delete = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Delete',
                request_serializer=examples_dot_internal_dot_proto_dot_sub2_dot_message__pb2.IdMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetQuery = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetQuery',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetRepeatedQuery = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetRepeatedQuery',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverythingRepeated.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverythingRepeated.FromString,
                )
        self.Echo = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Echo',
                request_serializer=examples_dot_internal_dot_proto_dot_sub_dot_message__pb2.StringMessage.SerializeToString,
                response_deserializer=examples_dot_internal_dot_proto_dot_sub_dot_message__pb2.StringMessage.FromString,
                )
        self.DeepPathEcho = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/DeepPathEcho',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                )
        self.NoBindings = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/NoBindings',
                request_serializer=google_dot_protobuf_dot_duration__pb2.Duration.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Timeout = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Timeout',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ErrorWithDetails = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/ErrorWithDetails',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetMessageWithBody = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetMessageWithBody',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.MessageWithBody.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.PostWithEmptyBody = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/PostWithEmptyBody',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.Body.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CheckGetQueryParams = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckGetQueryParams',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                )
        self.CheckNestedEnumGetQueryParams = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckNestedEnumGetQueryParams',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                )
        self.CheckPostQueryParams = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckPostQueryParams',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                )
        self.OverwriteResponseContentType = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/OverwriteResponseContentType',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.CheckExternalPathEnum = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckExternalPathEnum',
                request_serializer=examples_dot_internal_dot_proto_dot_pathenum_dot_path__enum__pb2.MessageWithPathEnum.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CheckExternalNestedPathEnum = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckExternalNestedPathEnum',
                request_serializer=examples_dot_internal_dot_proto_dot_pathenum_dot_path__enum__pb2.MessageWithNestedPathEnum.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ABitOfEverythingServiceServicer(object):
    """ABitOfEverything service is used to validate that APIs with complicated
    proto messages and URL templates are still processed correctly.
    """

    def Create(self, request, context):
        """Create a new ABitOfEverything

        This API creates a new ABitOfEverything
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBody(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRepeatedQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """Echo allows posting a StringMessage value.

        It also exposes multiple bindings.

        This makes it useful when validating that the OpenAPI v2 API
        description exposes documentation correctly on all paths
        defined as additional_bindings in the proto.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeepPathEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NoBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Timeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ErrorWithDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageWithBody(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostWithEmptyBody(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckGetQueryParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckNestedEnumGetQueryParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPostQueryParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OverwriteResponseContentType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckExternalPathEnum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckExternalNestedPathEnum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ABitOfEverythingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            ),
            'CreateBody': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBody,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=examples_dot_internal_dot_proto_dot_sub2_dot_message__pb2.IdMessage.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateV2': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateV2,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.UpdateV2Request.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=examples_dot_internal_dot_proto_dot_sub2_dot_message__pb2.IdMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuery,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetRepeatedQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepeatedQuery,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverythingRepeated.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverythingRepeated.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=examples_dot_internal_dot_proto_dot_sub_dot_message__pb2.StringMessage.FromString,
                    response_serializer=examples_dot_internal_dot_proto_dot_sub_dot_message__pb2.StringMessage.SerializeToString,
            ),
            'DeepPathEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.DeepPathEcho,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            ),
            'NoBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.NoBindings,
                    request_deserializer=google_dot_protobuf_dot_duration__pb2.Duration.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Timeout': grpc.unary_unary_rpc_method_handler(
                    servicer.Timeout,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ErrorWithDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.ErrorWithDetails,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMessageWithBody': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageWithBody,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.MessageWithBody.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PostWithEmptyBody': grpc.unary_unary_rpc_method_handler(
                    servicer.PostWithEmptyBody,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.Body.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CheckGetQueryParams': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckGetQueryParams,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            ),
            'CheckNestedEnumGetQueryParams': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckNestedEnumGetQueryParams,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            ),
            'CheckPostQueryParams': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPostQueryParams,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            ),
            'OverwriteResponseContentType': grpc.unary_unary_rpc_method_handler(
                    servicer.OverwriteResponseContentType,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'CheckExternalPathEnum': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckExternalPathEnum,
                    request_deserializer=examples_dot_internal_dot_proto_dot_pathenum_dot_path__enum__pb2.MessageWithPathEnum.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CheckExternalNestedPathEnum': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckExternalNestedPathEnum,
                    request_deserializer=examples_dot_internal_dot_proto_dot_pathenum_dot_path__enum__pb2.MessageWithNestedPathEnum.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.gateway.examples.internal.examplepb.ABitOfEverythingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ABitOfEverythingService(object):
    """ABitOfEverything service is used to validate that APIs with complicated
    proto messages and URL templates are still processed correctly.
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Create',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CreateBody',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Lookup',
            examples_dot_internal_dot_proto_dot_sub2_dot_message__pb2.IdMessage.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Update',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/UpdateV2',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.UpdateV2Request.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Delete',
            examples_dot_internal_dot_proto_dot_sub2_dot_message__pb2.IdMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetQuery',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRepeatedQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetRepeatedQuery',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverythingRepeated.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverythingRepeated.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Echo',
            examples_dot_internal_dot_proto_dot_sub_dot_message__pb2.StringMessage.SerializeToString,
            examples_dot_internal_dot_proto_dot_sub_dot_message__pb2.StringMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeepPathEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/DeepPathEcho',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NoBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/NoBindings',
            google_dot_protobuf_dot_duration__pb2.Duration.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Timeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Timeout',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ErrorWithDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/ErrorWithDetails',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessageWithBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetMessageWithBody',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.MessageWithBody.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostWithEmptyBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/PostWithEmptyBody',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.Body.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckGetQueryParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckGetQueryParams',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckNestedEnumGetQueryParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckNestedEnumGetQueryParams',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckPostQueryParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckPostQueryParams',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_a__bit__of__everything__pb2.ABitOfEverything.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OverwriteResponseContentType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/OverwriteResponseContentType',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckExternalPathEnum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckExternalPathEnum',
            examples_dot_internal_dot_proto_dot_pathenum_dot_path__enum__pb2.MessageWithPathEnum.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckExternalNestedPathEnum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckExternalNestedPathEnum',
            examples_dot_internal_dot_proto_dot_pathenum_dot_path__enum__pb2.MessageWithNestedPathEnum.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class camelCaseServiceNameStub(object):
    """camelCase and lowercase service names are valid but not recommended (use TitleCase instead)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Empty = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.camelCaseServiceName/Empty',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class camelCaseServiceNameServicer(object):
    """camelCase and lowercase service names are valid but not recommended (use TitleCase instead)
    """

    def Empty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_camelCaseServiceNameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Empty': grpc.unary_unary_rpc_method_handler(
                    servicer.Empty,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.gateway.examples.internal.examplepb.camelCaseServiceName', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class camelCaseServiceName(object):
    """camelCase and lowercase service names are valid but not recommended (use TitleCase instead)
    """

    @staticmethod
    def Empty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.camelCaseServiceName/Empty',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class AnotherServiceWithNoBindingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NoBindings = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.AnotherServiceWithNoBindings/NoBindings',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AnotherServiceWithNoBindingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NoBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnotherServiceWithNoBindingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NoBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.NoBindings,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.gateway.examples.internal.examplepb.AnotherServiceWithNoBindings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnotherServiceWithNoBindings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NoBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.AnotherServiceWithNoBindings/NoBindings',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
