# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_gateway.examples.internal.proto.examplepb import response_body_service_pb2 as grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2


class ResponseBodyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResponseBody = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ResponseBodyService/GetResponseBody',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyOut.FromString,
                )
        self.ListResponseBodies = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ResponseBodyService/ListResponseBodies',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.RepeatedResponseBodyOut.FromString,
                )
        self.ListResponseStrings = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ResponseBodyService/ListResponseStrings',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.RepeatedResponseStrings.FromString,
                )
        self.GetResponseBodyStream = channel.unary_stream(
                '/grpc.gateway.examples.internal.examplepb.ResponseBodyService/GetResponseBodyStream',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyOut.FromString,
                )


class ResponseBodyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetResponseBody(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResponseBodies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResponseStrings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResponseBodyStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResponseBodyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResponseBody': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResponseBody,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyOut.SerializeToString,
            ),
            'ListResponseBodies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResponseBodies,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.RepeatedResponseBodyOut.SerializeToString,
            ),
            'ListResponseStrings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResponseStrings,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.RepeatedResponseStrings.SerializeToString,
            ),
            'GetResponseBodyStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetResponseBodyStream,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyOut.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.gateway.examples.internal.examplepb.ResponseBodyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResponseBodyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetResponseBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ResponseBodyService/GetResponseBody',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyOut.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListResponseBodies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ResponseBodyService/ListResponseBodies',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.RepeatedResponseBodyOut.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListResponseStrings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ResponseBodyService/ListResponseStrings',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.RepeatedResponseStrings.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResponseBodyStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.gateway.examples.internal.examplepb.ResponseBodyService/GetResponseBodyStream',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyIn.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_response__body__service__pb2.ResponseBodyOut.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
