# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_gateway.examples.internal.proto.examplepb import swagger_merge_b_pb2 as grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2


class ServiceBStub(object):
    """ServiceB service responds to incoming merge requests.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MethodOne = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ServiceB/MethodOne',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.InMessageB.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.OutMessageB.FromString,
                )
        self.MethodTwo = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.ServiceB/MethodTwo',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.OutMessageB.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.InMessageB.FromString,
                )


class ServiceBServicer(object):
    """ServiceB service responds to incoming merge requests.
    """

    def MethodOne(self, request, context):
        """ServiceB.MethodOne receives InMessageB and returns OutMessageB

        Here is the detail explanation about ServiceB.MethodOne.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MethodTwo(self, request, context):
        """ServiceB.MethodTwo receives OutMessageB and returns InMessageB

        Here is the detail explanation about ServiceB.MethodTwo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MethodOne': grpc.unary_unary_rpc_method_handler(
                    servicer.MethodOne,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.InMessageB.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.OutMessageB.SerializeToString,
            ),
            'MethodTwo': grpc.unary_unary_rpc_method_handler(
                    servicer.MethodTwo,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.OutMessageB.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.InMessageB.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.gateway.examples.internal.examplepb.ServiceB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceB(object):
    """ServiceB service responds to incoming merge requests.
    """

    @staticmethod
    def MethodOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ServiceB/MethodOne',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.InMessageB.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.OutMessageB.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MethodTwo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.ServiceB/MethodTwo',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.OutMessageB.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_swagger__merge__b__pb2.InMessageB.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
