# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_gateway.examples.internal.proto.examplepb import unannotated_echo_service_pb2 as grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2


class UnannotatedEchoServiceStub(object):
    """Echo service responds to incoming echo requests.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.UnannotatedEchoService/Echo',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
                )
        self.EchoBody = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.UnannotatedEchoService/EchoBody',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
                )
        self.EchoDelete = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.UnannotatedEchoService/EchoDelete',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
                )


class UnannotatedEchoServiceServicer(object):
    """Echo service responds to incoming echo requests.
    """

    def Echo(self, request, context):
        """Echo method receives a simple message and returns it.

        The message posted as the id parameter will also be
        returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoBody(self, request, context):
        """EchoBody method receives a simple message and returns it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoDelete(self, request, context):
        """EchoDelete method receives a simple message and returns it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnannotatedEchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
            ),
            'EchoBody': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoBody,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
            ),
            'EchoDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoDelete,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.gateway.examples.internal.examplepb.UnannotatedEchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnannotatedEchoService(object):
    """Echo service responds to incoming echo requests.
    """

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.UnannotatedEchoService/Echo',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EchoBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.UnannotatedEchoService/EchoBody',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EchoDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.UnannotatedEchoService/EchoDelete',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_unannotated__echo__service__pb2.UnannotatedSimpleMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
