# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from grpc_gateway.examples.internal.proto.examplepb import wrappers_pb2 as grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_wrappers__pb2


class WrappersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/Create',
                request_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_wrappers__pb2.Wrappers.SerializeToString,
                response_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_wrappers__pb2.Wrappers.FromString,
                )
        self.CreateStringValue = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateStringValue',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.CreateInt32Value = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateInt32Value',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                )
        self.CreateInt64Value = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateInt64Value',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.FromString,
                )
        self.CreateFloatValue = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateFloatValue',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.FloatValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.FloatValue.FromString,
                )
        self.CreateDoubleValue = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateDoubleValue',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.DoubleValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.DoubleValue.FromString,
                )
        self.CreateBoolValue = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateBoolValue',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                )
        self.CreateUInt32Value = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateUInt32Value',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                )
        self.CreateUInt64Value = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateUInt64Value',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.FromString,
                )
        self.CreateBytesValue = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateBytesValue',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.BytesValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BytesValue.FromString,
                )
        self.CreateEmpty = channel.unary_unary(
                '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateEmpty',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class WrappersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStringValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInt32Value(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInt64Value(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFloatValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDoubleValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBoolValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUInt32Value(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUInt64Value(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBytesValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmpty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WrappersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_wrappers__pb2.Wrappers.FromString,
                    response_serializer=grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_wrappers__pb2.Wrappers.SerializeToString,
            ),
            'CreateStringValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStringValue,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'CreateInt32Value': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInt32Value,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            ),
            'CreateInt64Value': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInt64Value,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.SerializeToString,
            ),
            'CreateFloatValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFloatValue,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.FloatValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.FloatValue.SerializeToString,
            ),
            'CreateDoubleValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDoubleValue,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.DoubleValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.DoubleValue.SerializeToString,
            ),
            'CreateBoolValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBoolValue,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'CreateUInt32Value': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUInt32Value,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            ),
            'CreateUInt64Value': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUInt64Value,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.SerializeToString,
            ),
            'CreateBytesValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBytesValue,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.BytesValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BytesValue.SerializeToString,
            ),
            'CreateEmpty': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmpty,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.gateway.examples.internal.examplepb.WrappersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WrappersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/Create',
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_wrappers__pb2.Wrappers.SerializeToString,
            grpc__gateway_dot_examples_dot_internal_dot_proto_dot_examplepb_dot_wrappers__pb2.Wrappers.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateStringValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateStringValue',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateInt32Value(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateInt32Value',
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateInt64Value(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateInt64Value',
            google_dot_protobuf_dot_wrappers__pb2.Int64Value.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.Int64Value.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateFloatValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateFloatValue',
            google_dot_protobuf_dot_wrappers__pb2.FloatValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.FloatValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDoubleValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateDoubleValue',
            google_dot_protobuf_dot_wrappers__pb2.DoubleValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.DoubleValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBoolValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateBoolValue',
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUInt32Value(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateUInt32Value',
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUInt64Value(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateUInt64Value',
            google_dot_protobuf_dot_wrappers__pb2.UInt64Value.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.UInt64Value.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBytesValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateBytesValue',
            google_dot_protobuf_dot_wrappers__pb2.BytesValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BytesValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEmpty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.gateway.examples.internal.examplepb.WrappersService/CreateEmpty',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
