# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc-gateway/examples/internal/proto/pathenum/path_enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc-gateway/examples/internal/proto/pathenum/path_enum.proto',
  package='grpc.gateway.examples.internal.pathenum',
  syntax='proto3',
  serialized_options=b'ZGgithub.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/pathenum',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=grpc-gateway/examples/internal/proto/pathenum/path_enum.proto\x12\'grpc.gateway.examples.internal.pathenum\"5\n\x0fMessagePathEnum\"\"\n\x0eNestedPathEnum\x12\x07\n\x03GHI\x10\x00\x12\x07\n\x03JKL\x10\x01\"W\n\x13MessageWithPathEnum\x12@\n\x05value\x18\x01 \x01(\x0e\x32\x31.grpc.gateway.examples.internal.pathenum.PathEnum\"s\n\x19MessageWithNestedPathEnum\x12V\n\x05value\x18\x01 \x01(\x0e\x32G.grpc.gateway.examples.internal.pathenum.MessagePathEnum.NestedPathEnum*\x1c\n\x08PathEnum\x12\x07\n\x03\x41\x42\x43\x10\x00\x12\x07\n\x03\x44\x45\x46\x10\x01\x42IZGgithub.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/pathenumb\x06proto3'
)

_PATHENUM = _descriptor.EnumDescriptor(
  name='PathEnum',
  full_name='grpc.gateway.examples.internal.pathenum.PathEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ABC', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=367,
  serialized_end=395,
)
_sym_db.RegisterEnumDescriptor(_PATHENUM)

PathEnum = enum_type_wrapper.EnumTypeWrapper(_PATHENUM)
ABC = 0
DEF = 1


_MESSAGEPATHENUM_NESTEDPATHENUM = _descriptor.EnumDescriptor(
  name='NestedPathEnum',
  full_name='grpc.gateway.examples.internal.pathenum.MessagePathEnum.NestedPathEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GHI', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JKL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=125,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEPATHENUM_NESTEDPATHENUM)


_MESSAGEPATHENUM = _descriptor.Descriptor(
  name='MessagePathEnum',
  full_name='grpc.gateway.examples.internal.pathenum.MessagePathEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGEPATHENUM_NESTEDPATHENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=159,
)


_MESSAGEWITHPATHENUM = _descriptor.Descriptor(
  name='MessageWithPathEnum',
  full_name='grpc.gateway.examples.internal.pathenum.MessageWithPathEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.gateway.examples.internal.pathenum.MessageWithPathEnum.value', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=248,
)


_MESSAGEWITHNESTEDPATHENUM = _descriptor.Descriptor(
  name='MessageWithNestedPathEnum',
  full_name='grpc.gateway.examples.internal.pathenum.MessageWithNestedPathEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.gateway.examples.internal.pathenum.MessageWithNestedPathEnum.value', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=365,
)

_MESSAGEPATHENUM_NESTEDPATHENUM.containing_type = _MESSAGEPATHENUM
_MESSAGEWITHPATHENUM.fields_by_name['value'].enum_type = _PATHENUM
_MESSAGEWITHNESTEDPATHENUM.fields_by_name['value'].enum_type = _MESSAGEPATHENUM_NESTEDPATHENUM
DESCRIPTOR.message_types_by_name['MessagePathEnum'] = _MESSAGEPATHENUM
DESCRIPTOR.message_types_by_name['MessageWithPathEnum'] = _MESSAGEWITHPATHENUM
DESCRIPTOR.message_types_by_name['MessageWithNestedPathEnum'] = _MESSAGEWITHNESTEDPATHENUM
DESCRIPTOR.enum_types_by_name['PathEnum'] = _PATHENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessagePathEnum = _reflection.GeneratedProtocolMessageType('MessagePathEnum', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEPATHENUM,
  '__module__' : 'grpc_gateway.examples.internal.proto.pathenum.path_enum_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.examples.internal.pathenum.MessagePathEnum)
  })
_sym_db.RegisterMessage(MessagePathEnum)

MessageWithPathEnum = _reflection.GeneratedProtocolMessageType('MessageWithPathEnum', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEWITHPATHENUM,
  '__module__' : 'grpc_gateway.examples.internal.proto.pathenum.path_enum_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.examples.internal.pathenum.MessageWithPathEnum)
  })
_sym_db.RegisterMessage(MessageWithPathEnum)

MessageWithNestedPathEnum = _reflection.GeneratedProtocolMessageType('MessageWithNestedPathEnum', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEWITHNESTEDPATHENUM,
  '__module__' : 'grpc_gateway.examples.internal.proto.pathenum.path_enum_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.examples.internal.pathenum.MessageWithNestedPathEnum)
  })
_sym_db.RegisterMessage(MessageWithNestedPathEnum)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
