# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc-gateway/examples/internal/proto/sub2/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc-gateway/examples/internal/proto/sub2/message.proto',
  package='sub2',
  syntax='proto3',
  serialized_options=b'ZCgithub.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/sub2',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n7grpc-gateway/examples/internal/proto/sub2/message.proto\x12\x04sub2\"\x19\n\tIdMessage\x12\x0c\n\x04uuid\x18\x01 \x01(\tBEZCgithub.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/sub2b\x06proto3'
)




_IDMESSAGE = _descriptor.Descriptor(
  name='IdMessage',
  full_name='sub2.IdMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='sub2.IdMessage.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['IdMessage'] = _IDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdMessage = _reflection.GeneratedProtocolMessageType('IdMessage', (_message.Message,), {
  'DESCRIPTOR' : _IDMESSAGE,
  '__module__' : 'grpc_gateway.examples.internal.proto.sub2.message_pb2'
  # @@protoc_insertion_point(class_scope:sub2.IdMessage)
  })
_sym_db.RegisterMessage(IdMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
