# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc-gateway/examples/internal/helloworld/helloworld.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc-gateway/examples/internal/helloworld/helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n:grpc-gateway/examples/internal/helloworld/helloworld.proto\x12\nhelloworld\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc6\x03\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12,\n\x06strVal\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x08\x66loatVal\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12/\n\tdoubleVal\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12+\n\x07\x62oolVal\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12-\n\x08\x62ytesVal\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.BytesValue\x12-\n\x08int32Val\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\tuint32Val\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12-\n\x08int64Val\x18\t \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12/\n\tuint64Val\x18\n \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xdb\x02\n\x07Greeter\x12\xcf\x02\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x90\x02\x82\xd3\xe4\x93\x02\x89\x02\x12\x0b/say/{name}Z\x16\x12\x14/say/strval/{strVal}Z\x1a\x12\x18/say/floatval/{floatVal}Z\x1c\x12\x1a/say/doubleval/{doubleVal}Z\x18\x12\x16/say/boolval/{boolVal}Z\x1a\x12\x18/say/bytesval/{bytesVal}Z\x1a\x12\x18/say/int32val/{int32Val}Z\x1c\x12\x1a/say/uint32val/{uint32Val}Z\x1a\x12\x18/say/int64val/{int64Val}Z\x1c\x12\x1a/say/uint64val/{uint64Val}b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='helloworld.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strVal', full_name='helloworld.HelloRequest.strVal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='floatVal', full_name='helloworld.HelloRequest.floatVal', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='doubleVal', full_name='helloworld.HelloRequest.doubleVal', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boolVal', full_name='helloworld.HelloRequest.boolVal', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytesVal', full_name='helloworld.HelloRequest.bytesVal', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int32Val', full_name='helloworld.HelloRequest.int32Val', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uint32Val', full_name='helloworld.HelloRequest.uint32Val', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int64Val', full_name='helloworld.HelloRequest.int64Val', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uint64Val', full_name='helloworld.HelloRequest.uint64Val', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=591,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='helloworld.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=622,
)

_HELLOREQUEST.fields_by_name['strVal'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_HELLOREQUEST.fields_by_name['floatVal'].message_type = google_dot_protobuf_dot_wrappers__pb2._FLOATVALUE
_HELLOREQUEST.fields_by_name['doubleVal'].message_type = google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE
_HELLOREQUEST.fields_by_name['boolVal'].message_type = google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE
_HELLOREQUEST.fields_by_name['bytesVal'].message_type = google_dot_protobuf_dot_wrappers__pb2._BYTESVALUE
_HELLOREQUEST.fields_by_name['int32Val'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_HELLOREQUEST.fields_by_name['uint32Val'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_HELLOREQUEST.fields_by_name['int64Val'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT64VALUE
_HELLOREQUEST.fields_by_name['uint64Val'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT64VALUE
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'grpc_gateway.examples.internal.helloworld.helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'grpc_gateway.examples.internal.helloworld.helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=625,
  serialized_end=972,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='helloworld.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=b'\202\323\344\223\002\211\002\022\013/say/{name}Z\026\022\024/say/strval/{strVal}Z\032\022\030/say/floatval/{floatVal}Z\034\022\032/say/doubleval/{doubleVal}Z\030\022\026/say/boolval/{boolVal}Z\032\022\030/say/bytesval/{bytesVal}Z\032\022\030/say/int32val/{int32Val}Z\034\022\032/say/uint32val/{uint32Val}Z\032\022\030/say/int64val/{int64Val}Z\034\022\032/say/uint64val/{uint64Val}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
